🔀 :: 쿠키 생성 기능
Team-RunningTomato/Team-RunningTomato-Running-Tomato-BackEnd pull request #16
Opened 2024-12-10 06:36 UTC by yena5511

## 💡 배경 및 개요

쿠키 생성하는 기능을 추가하였습니다.

Resolves: #15 

## 📃 작업내용

- 쿠키 생성 기능 코드 추가
- 
## 🙋‍♂️ 리뷰노트

## ✅ PR 체크리스트

> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!

- [ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g.  `노션`, `README`)
- [ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"환경값 추가되었어요"`)
- [ ] 작업한 코드가 정상적으로 동작하나요?
- [ ] Merge 대상 브랜치가 올바른가요?
- [ ] PR과 관련 없는 작업이 있지는 않나요?

## 🎸 기타

2024-12-10 08:25 UTC, Umjiseung requested changes
피드백 반영해서 수정 부탁드립니다!

2024-12-10 08:25 UTC, Umjiseung commented on src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
> +
```suggestion
```

2024-12-10 08:25 UTC, Umjiseung commented on src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(null);
badReqeust보단 서버에러로 하는게 오히려 나을 수도 있을거같아요
이건 잘못된 요청보단..음 로직 오류로 생기는 게 더 적절할 것 같아요

2024-12-10 08:25 UTC, Umjiseung commented on src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(null);
그리고 공백 정리 부탁드립니다

2024-12-10 15:59 UTC, yena5511 commented on src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(null);
bcb0750b37d80070f24bf4d2015d7e9bcbb72484
수정했습니다!!

2024-12-11 00:10 UTC, Umjiseung approved these changes
수고하셨습니다!

2024-12-11 00:39 UTC, merged