🔀 :: 런닝 모집글 취소
Team-RunningTomato/Team-RunningTomato-Running-Tomato-BackEnd pull request #46
Opened 2024-12-22 14:42 UTC by yena5511

## 💡 배경 및 개요

> 런닝 모집글 취소 api를 구현했습니다

Resolves: #45 

## 📃 작업내용

> deleteApplicationMeeting api 추가

## 🙋‍♂️ 리뷰노트

## ✅ PR 체크리스트

> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!

- [x] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g.  `노션`, `README`)
- [x] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"환경값 추가되었어요"`)
- [x] 작업한 코드가 정상적으로 동작하나요?
- [x] Merge 대상 브랜치가 올바른가요?
- [x] PR과 관련 없는 작업이 있지는 않나요?

## 🎸 기타

2024-12-22 23:49 UTC, Umjiseung requested changes
코드리뷰 반영부탁드립니다!

2024-12-22 23:49 UTC, Umjiseung commented on src/main/java/com/tomato/running/domain/meeting/service/DeleteApplicationMeetingService.java
> +
쿼리를 이렇게 날리게 되면 meetingMember에 존재하는 데이터 중에 meeting과 관련된 데이터들이 다 삭제될 것 같습니다
이 쿼리보다는 deleteByMeetingAndUser 이런식으로 해야지 해당 데이터만 지워질 것 같습니다

2024-12-23 00:09 UTC, yena5511 commented on src/main/java/com/tomato/running/domain/meeting/service/DeleteApplicationMeetingService.java
> +
수정했습니다 [4e88181](https://github.com/Team-RunningTomato/Team-RunningTomato-Running-Tomato-BackEnd/pull/46/commits/4e88181f2c72b85a806b2eeeac293e30ef74ab3a)

2024-12-23 00:10 UTC, Umjiseung approved these changes
수고하셨어요!

2024-12-23 00:11 UTC, merged